// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMPtKa7gXfGQC0yybZz92Dh_TNw5eqgE',
    appId: '1:879597983428:web:fb1e901382cc51324f9b91',
    messagingSenderId: '879597983428',
    projectId: 'food-boxes-ios',
    authDomain: 'food-boxes-ios.firebaseapp.com',
    storageBucket: 'food-boxes-ios.appspot.com',
    measurementId: 'G-JPZS99ZBEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBO7tif-6L1Lbv1ej688sqBpOIqegnbic',
    appId: '1:879597983428:android:4d7105a250bec7e54f9b91',
    messagingSenderId: '879597983428',
    projectId: 'food-boxes-ios',
    storageBucket: 'food-boxes-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gDSvO5kdF-1vOePAianUhawYKuEu2qM',
    appId: '1:879597983428:ios:b3dc7abdd5dc585e4f9b91',
    messagingSenderId: '879597983428',
    projectId: 'food-boxes-ios',
    storageBucket: 'food-boxes-ios.appspot.com',
    iosClientId: '879597983428-6l2lau0k99diib4amudcclc7moa2p3h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBoxes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3gDSvO5kdF-1vOePAianUhawYKuEu2qM',
    appId: '1:879597983428:ios:b3dc7abdd5dc585e4f9b91',
    messagingSenderId: '879597983428',
    projectId: 'food-boxes-ios',
    storageBucket: 'food-boxes-ios.appspot.com',
    iosClientId: '879597983428-6l2lau0k99diib4amudcclc7moa2p3h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBoxes',
  );
}
